---
  - name: add address
    command: |
      ssh {{ mikrotik_user }}@{{ mikrotik_router }} -p {{ mikrotik_router_port }}
      '/ip address add address={{ address }}/{{ mask }} interface={{ interface }}'
    tags: add-address
